version: '3'
services:
  zookeeper-kafka:
    hostname: zookeeper-kafka
    container_name: zookeeper-kafka
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - pipeline-data-net
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kafka:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pipeline-data-net

networks:
  pipeline-data-net:
    driver: bridge
